---
# Variable setup.
- name: Include variables
  include_vars: "Windows.yml"

# Setup/install tasks.
- include: install-packages.yml

# Configure Jenkins init settings.
- include: settings.yml

# Make sure Jenkins starts, then configure Jenkins.
- name: Ensure Jenkins is started and runs on startup.
  win_service: name=jenkins state=started enabled=yes

# - name: Wait for Jenkins to start up before proceeding.
#   raw: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
#   register: result
#   until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
#   retries: "{{ jenkins_connection_retries }}"
#   delay: "{{ jenkins_connection_delay }}"
#   changed_when: false

- name: Get the jenkins-cli jarfile from the Jenkins server.
  win_get_url:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"

# Update Jenkins and install configured plugins.
- include: plugins.yml

#and finaly restart jenkins
- name: Ensure Jenkins is re-started.
  win_service: name=jenkins state=restarted enabled=yes
